Hw sql.2
Allduiin/Internet-shop pull request #18
Opened 2020-05-14 14:32 UTC by Allduiin

2020-05-14 20:03 UTC, boroda4436 requested changes

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +        try (Connection connection = ConnectionUtil.getConnection()) {
Навіщо тобі тут коннекшн якщо ти його не використовуєш?

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +        Long orderId;
Пам1ятаєш ми говорили чому так погано робити?

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +                orderId = resultSet.getLong(1);
```suggestion
                Long orderId = resultSet.getLong(1);
```

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +                        resultSet.getLong(2), getProductsByOrderId(orderId)));
та ж штука з перформансом що і в Макса Матуляка і в Ігоря Миненка

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +                        resultSet.getLong(2), getProductsByOrderId(orderId)));
воно то працює, я не спорю) Просто хочу щоб ви розуміли що тут є проблема і в чому її причина

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +        String query = "UPDATE orders SET user_id = ? WHERE order_id = ?;";
немає сенсу. Користувач в замолення навряд чи зміниться

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +            query = "DELETE FROM orders_products WHERE order_id = ?;";
якщо видаляєш, то може треба потім і вставити нові значення?

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        Product product;
не роби так)

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +            product = getProductFromResultSet(resultSet);
```suggestion
            Product product = getProductFromResultSet(resultSet);
```

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        PreparedStatement statement = connection.prepareStatement(query);
Чому без try(...) ?

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +    private int doQueryWithId(String query, Long id,Connection connection) throws SQLException {
```suggestion
    private int doQueryWithId(String query, Long id, Connection connection) throws SQLException {
```
чекстайл запускав?

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +        Long cartId;
ннннєєєєєт)

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +        List<Product> products;
ннннєєєєєт)

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +        try (Connection connection = ConnectionUtil.getConnection()) {
знову. описував вище схожий кейс

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +        Long cartId;
...

2020-05-14 20:03 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/UserDaoJdbcImpl.java
> +        String query = "INSERT INTO users_roles ( user_id, role_id) VALUES (?,?)";
```suggestion
        String query = "INSERT INTO users_roles (user_id, role_id) VALUES (?,?)";
```

2020-05-15 06:11 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +        Long orderId;
Нет не помню((

2020-05-15 06:12 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +                orderId = resultSet.getLong(1);
А зачем нам создавать новый лонг на каждую переменную

2020-05-15 06:32 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +                        resultSet.getLong(2), getProductsByOrderId(orderId)));
Бодь прочитал что писал понял в чем суть проблемы, но ты вроде вчера на Q&A что так можно делать, я поменяю на два вайла

2020-05-15 06:53 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +            query = "DELETE FROM orders_products WHERE order_id = ?;";
Ну я и вставляю методом addProducts(order, connection)

2020-05-15 06:55 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        Product product;
Странно у меня по чему то в данный момент поменялся этот код хотя я его не менял

2020-05-15 06:55 UTC, Allduiin commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        Product product;
Магия))

2020-05-15 08:05 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/OrderDaoJdbsImpl.java
> +            query = "DELETE FROM orders_products WHERE order_id = ?;";
не побачив. Сорі!

2020-05-15 08:05 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        int result;
не треба так(

2020-05-15 08:06 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ProductDaoJdbcImpl.java
> +        PreparedStatement statement = connection.prepareStatement(query);
а тут?

2020-05-15 08:07 UTC, boroda4436 requested changes

2020-05-15 08:07 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +            List<Product> products;
а тут?

2020-05-15 08:07 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +            Long cartId;
тут?

2020-05-15 08:07 UTC, boroda4436 commented on src/main/java/internetshop/dao/impl/ShoppingCartDaoJdbcImpl.java
> +            Long cartId;
тут?

2020-05-15 09:29 UTC, boroda4436 approved these changes

2020-05-17 13:13 UTC, merged